name: Get Citation Data (Manual)

on: 
 workflow_dispatch:  # 手动触发
 schedule:
  - cron:  '0 8 1 * *'  # 每月1号上午8点运行（备用）

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd ./google_scholar_crawler
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Google Scholar crawler
      run: |
        cd ./google_scholar_crawler
        python main.py
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        SCHOLAR_TIMEOUT_SECONDS: 600
        
    - name: Commit and push results
      if: success()
      run: |
        cd ./google_scholar_crawler/results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Manual Update Citation Data - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
